### ISSUE TITLE
browserify it

### ISSUE THREAD

**Issue by JBaczuk** [JBaczuk/bscript-parser#43]
This needs to be able to run in a browser for `bitcoin-script-js`

**Comment by wardlem** [comment]
@JBaczuk For `bitcoin-script-js` we should be able to `require` it from that project and bundle it there.  We could bundle it if somebody wants to add it a `<script>` tag in some other project.  I lean towards not wanting to commit the build file but instead offer an NPM script that will do this with documentation on how to generate it if somebody else wants to do it for their project.  However, I could be convinced otherwise.

**Comment by JBaczuk** [comment]
You're right, let's bundle it in `bitcoin-script-js`. Others can bundle it similarly
