### ISSUE TITLE
Change project name

### ISSUE THREAD

**Issue by JBaczuk** [JBaczuk/bscript-parser#66]
I'm thinking it would be nice to have the projects designated as `assembler` and `interpreter`, if there are some good names that would make sense. I know this project does more than an assembler, but I think it would help delineate the functionality. @wardlem  o you have any ideas/preferences?

**Comment by ghost** [comment]
@JBaczuk The roles of the two projects are a bit confusing.  This project does, in fact, parse bscript which makes me think `bscript-parser` is appropriate, though `bscript-assembler` makes sense to me as well.  It would make sense to rename the other project to `bscript-interpreter`.  There is some functionality in the project that I feel could be moved to their own stand-alone project (e.g. the opcodes module).  I also think it would be great to have an overarching project, `bscript` that contains the combined cli for all the projects.

I think what it comes down to, and perhaps a minor point of disconnect between the two of us is how the two projects are conceived.  What I was envisioning was that this module would parse a script (raw or assembly) into a token stream that the interpreter would interpret.  However, it seems that you are envisioning this module converting assembly into raw bytecode, and the interpreter directly interpreting the bytecode.  With my original vision, I think `bscript-parser` makes more sense, but with yours `bscript-assembler` makes more sense.  I believe that we have already decided to go with your vision; as such, I vote to change the project to `bscript-assembler`.

**Comment by JBaczuk** [comment]
@wardlem Yeah, I have no problem either way, I just need help understanding how the token stream approach works, could you help me understand the purpose of having it as a token stream rather than a buffer of bytes? I know it's a common approach, I just don't really understand best practices for tokenization, etc.

**Comment by ghost** [comment]
@JBaczuk A compiler typically goes through the following steps:

1. Lex (raw source -> token stream)
2. Parsing (token stream -> abstract syntax tree)
3. Compilation (abstract syntax tree -> target format [intermediate language, bytecode, or machine code])
4. (For interpreted languages) Execution (abstract syntax tree or bytecode instructions are executed by interpreter)

Also, steps 2 (parsing) and 3 (compilation) above are sometimes skipped for interpreted languages.

BScript is really a bytecode, which means it doesn't really make sense to lex it and convert it into tokens before executing.  The only reason I believed that it might for this project was because of how I was imagining the user interface would work.  In my mind's eye, I was seeing the user go step by step through a script with the assembly and raw hex being highlighted for each opcode.  Performing this visualization is easier to do if you have pre-parsed the script as a whole and you know where each semantic element of the script begins and ends.

**Comment by ghost** [comment]
I actually think we have at leat three projects here:

1. `bscript-assembler`
2. `bscript-interpreter`
3. `bscript-console` (the user interface)

The `bscript-console` project would be a web page that utilizes both the `bscript-interpreter` and `bscript-assembler` projects.  In fact, the two should be completely decoupled, and any functionality common to both (opcodes?) should be moved to yet another library.

I think my problem was thinking the [bitcoin-script-js](https://github.com/JBaczuk/bitcoin-script-js) project was going to include the user interface when it seems that it will only be the interpreter.

**Comment by JBaczuk** [comment]
Ok, yeah that makes sense to me. So maybe put `opcode_info_map.js` in its own module?

**Comment by ghost** [comment]
> Ok, yeah that makes sense to me. So maybe put opcode_info_map.js in its own module?

Yes, along with the `opcodes.js` library and everything associated with it.

**Comment by JBaczuk** [comment]
Ok I created all of the repositories:

- https://github.com/JBaczuk/bscript-assembler
- https://github.com/JBaczuk/bscript-interpreter
- https://github.com/JBaczuk/bscript-console
- https://github.com/JBaczuk/bscript-opcodes
